# Generated by Django 5.1 on 2024-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('artista', models.CharField(max_length=255)),
                ('duracao', models.TimeField()),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('logo', models.URLField()),
            ],
        ),
    ]
